### ISSUE TITLE
virtual-dom not listed as dependency

### ISSUE THREAD

**Issue by passy** [slamdata/purescript-halogen#51]
Hey, I was wondering if there's a reason why `virtual-dom` is not listed as explicit dependency. In order to build the examples, you currently have to run

```
npm install
npm install virtual-dom
gulp
```

Otherwise the build fails with a rather surprising

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: module "virtual-dom/create-element" not found from "/Users/phartig/Projects/purescript/purescript-halogen/fake_3ed802b1.js"
    at notFound (/Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/index.js:803:15)
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/index.js:754:23
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:44:14
    at process (/Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:113:43)
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:122:21
    at load (/Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:54:43)
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:60:22
    at /Users/phartig/Projects/purescript/purescript-halogen/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:16:47
    at Object.oncomplete (fs.js:108:15)
```

As there a reason for this or is it an oversight? :)

**Comment by passy** [comment]
Thanks, @paf31! :)
